### ISSUE TITLE
Error sending log data - status code 403

### ISSUE THREAD

**Issue by nrandell** [newrelic-experimental/gatsby-build-newrelic#17]
## Description
I've configured as described and when I try a build on my local machine get a lot of errors saying

```
 ERROR

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403

```

The configuration is 
```
{
  resolve: 'gatsby-build-newrelic',
  options: {
    NR_INSERT_KEY: 'XXXXXXXXXXXX',
    NR_LICENSE_KEY: 'XXXXXXXXXXXXX',
    NR_ACCOUNT_ID: 'XXXXXXXX',
    SITE_NAME: 'jankstack',
    customTags: { gatsbySite: true }
  }
}
```

The command run from yarn is
```
cross-env GATSBY_STALL_TIMEOUT=60000 GATSBY_CONNECTION_TIMEOUT=60000 gatsby build --open-tracing-config-file ./node_modules/gatsby-build-newrelic/zipkin-local.js --graphql-tracing
```

## Steps to Reproduce

```
cls; yarn build
```

## Expected Behavior

Not to see the error messages

## Your Environment
Windows 10 latest updates
Yarn with latest packages

**Comment by rudouglas** [comment]
Hi @nrandell @kingkero thanks for getting in touch. A `403` would usually mean this is an unauthorised request. The `NEW_RELIC_LICENSE_KEY` is the one the plugin uses to send logs so i'm thinking maybe this is incorrect. When creating a new key you want to choose the one labelled `Ingest - License` from the dropdown. Once created the key itself should have `NRAL` at the end of it.

![Screenshot 09-10-2021 10-36-00](https://user-images.githubusercontent.com/17122543/136652972-c6bc73b9-a741-4c21-bfbc-65c4a30a6180.png)

There are a couple of keys you can generate in New Relic so this can be confusing, if there's any way we could make the instructions clearer let us know 😄
