### ISSUE TITLE
winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403

### ISSUE THREAD

**Issue by jpvajda** [newrelic-experimental/gatsby-build-newrelic#30]
## Description

When running `gatsby build` or `yarn start` on the New Relic OSS site locally, this error continually is shown in the console as the pages attempt to build

```
 ERROR 

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403


 ERROR 

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403


 ERROR 

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403


 ERROR 

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403

⠸ building schema
```

## Steps to Reproduce

- Pull down the code in[ this PR ](https://github.com/newrelic/opensource-website/pull/900)and run the above commands,
- review your terminal 

## Expected Behavior

These errors do not appear in the terminal

## Relevant Logs / Console output

see above. this errors is repeated over and over again. 🤷 

## Your Environment

```
 System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 3.9.1 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 15.0
  npmPackages:
    gatsby: ^4.0.0 => 4.4.0
    gatsby-build-newrelic: 1.1.16 => 1.1.16
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.4.0
    gatsby-plugin-manifest: ^4.4.0 => 4.4.0
    gatsby-plugin-mdx: ^3.4.0 => 3.4.0
    gatsby-plugin-offline: ^5.4.0 => 5.4.0
    gatsby-plugin-sass: ^4.8.0 => 4.14.0
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0
    gatsby-remark-copy-linked-files: ^5.4.0 => 5.4.0
    gatsby-remark-images: ^6.4.0 => 6.4.0
    gatsby-source-filesystem: ^4.4.0 => 4.4.0
    gatsby-source-github-api: ^1.0.0 => 1.0.0
    gatsby-transformer-json: ^4.4.0 => 4.4.0
```

**Comment by jpvajda** [comment]
This project currently doesn't have a dedicated maintainer team as it's experimental, but let me tag a few people that may have some insights into this. @rudouglas / @lazyplatypus 👋

**Comment by rudouglas** [comment]
@jpvajda This is an authentication issue it looks like, are you sure you are using staging account id and license key as you currently have `staging: true` in the config. This works for me locally and doesn't throw any errors from the plugin

**Comment by jpvajda** [comment]
We resolved this, I had some local  `bash_profile` variables set to export, that we overridden the required. plugin variables.
